# Generated by Django 4.2.5 on 2023-12-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descryption', models.TextField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[(1, 'Одежда'), (2, 'Куртка'), (3, 'Пуховик')], max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
