# Generated by Django 4.2.5 on 2023-12-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Куртка', 'Куртка'), ('Пуховик', 'Пуховик')], max_length=100),
        ),
    ]
