# Generated by Django 4.2.5 on 2023-12-20 11:14

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(limit_choices_to=shop.models.limit_category, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_category', to='shop.category'),
        ),
    ]
