# Generated by Django 4.2.5 on 2023-12-23 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_category', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='descryption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
