# Generated by Django 4.2.5 on 2024-02-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discont', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discontcard',
            name='accumulative',
            field=models.IntegerField(default=0),
        ),
    ]
