# Generated by Django 4.2.5 on 2024-02-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discont', '0002_discontcard_accumulative'),
    ]

    operations = [
        migrations.AddField(
            model_name='discontcard',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
