# Generated by Django 4.2.5 on 2023-12-24 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
    ]
